<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace tool_metadata;

defined('MOODLE_INTERNAL') || die();

/**
 * Class for mocking various files with test metadata.
 *
 * @package    tool_metadata
 * @copyright  2019 Tom Dickman <tomdickman@catalyst-au.net>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class mock_file_builder {

    public static function mock_pdf() {
        global $CFG, $SITE;

        require_once($CFG->libdir . '/pdflib.php');

        // Create test PDF.
        $doc = new \pdf();
        $doc->SetTitle('Test PDF');
        $doc->SetAuthor('Moodle ' . $CFG->release);
        $doc->SetCreator('Metadata API');
        $doc->SetKeywords('Moodle, PDF');
        $doc->SetSubject('This has been generated by Moodle.');
        $doc->SetMargins(15, 30);

        $doc->setPrintHeader(true);
        $doc->setHeaderMargin(10);
        $doc->setHeaderData('pix/moodlelogo.png', 40, $SITE->fullname, $CFG->wwwroot);

        $doc->setPrintFooter(true);
        $doc->setFooterMargin(10);

        $doc->Cell(0, 0, 'Test Content', 0, 1, 'C', 1);

        $buffer = $doc->Output('test.pdf', 'S');

        $fs = get_file_storage();
        $syscontext = \context_system::instance();
        $filerecord = array(
            'contextid' => $syscontext->id,
            'component' => 'tool_metadata',
            'filearea'  => 'unittest',
            'itemid'    => 0,
            'filepath'  => '/',
            'filename'  => 'test.pdf',
        );
        $file = $fs->create_file_from_string($filerecord, $buffer);
        unset($pdf);

        return $file;
    }

}